# Generated by Django 5.2.8 on 2025-11-18 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('NEW ARRIVALS', 'NEW ARRIVALS'), ('EXCLUSIVE', 'EXCLUSIVE'), ('SALE', 'SALE'), ('MAN', 'MAN'), ('WOMAN', 'WOMAN'), ('KIDS', 'KIDS'), ('COMING SOON', 'COMING SOON'), ('BRAND', 'BRAND')], default='NEW ARRIVALS', max_length=20),
        ),
    ]
